---
- name: Install Ansible PostgreSQL dependencies
  yum: name={{ item }} state=present
  with_items:
    - python-psycopg2

###
# PostgreSQL
###

- name: Install PostgreSQL 9.2
  yum: name={{ item }} state=present
  with_items:
    - postgresql92
    - postgresql92-server

- name: Initialize PostgreSQL database
  command: service postgresql-9.2 initdb sv_SE.utf8 creates=/var/lib/pgsql/9.2/data/PG_VERSION

- name: Add pg_hba.conf
  copy: src=pg_hba.conf dest=/var/lib/pgsql/9.2/data/pg_hba.conf owner=postgres group=postgres mode=600
  notify: Restart PostgreSQL

- name: Enable PostgreSQL service
  service: name=postgresql-9.2 enabled=yes state=started


###
# PostgreSQL databases and users
###

- name: Create application databases
  postgresql_db: name={{ item.name }}
  sudo: true
  sudo_user: postgres
  with_items: application.instances

- name: Create application database users
  postgresql_user: name={{ item.name }}
                   password={{ item.db_password }}
                   db={{ item.name }}
                   encrypted=false
  sudo: true
  sudo_user: postgres
  with_items: application.instances
